---
blank_issues_enabled: false
contact_links:
  - name: Heimdall Community Support
    url: https://github.com/starknet-exploration/heimdall/discussions
    about: Please ask and answer questions here.
